//! Live-instance accounting, exact.
//!
//! A tracked type carries a [`Census`] field. The field's construction
//! increments the type's live counter and one size bucket; its `Drop`
//! decrements both. Nothing samples, nothing estimates, and nothing walks the
//! heap, so what the UI draws is a histogram of the instances that are alive
//! right now rather than a histogram of the instances that were ever built.


/// The footprint of one instance.
///
/// The [`track`](crate::track) attribute generates an implementation returning
/// `size_of::<Self>()`, which is **the wrong number for any type that owns heap**.
/// See the crate documentation.
pub trait Measured {
    fn bytes(&self) -> usize;
}

/// Binds a type to its process-wide counters. Generated by
/// [`track`](crate::track); there is no reason to implement it by hand.
pub trait Tracked: Sized {
    fn slot() -> &'static TypeSlot;
}

#[cfg(feature = "enabled")]
mod imp {
    use super::{Measured, Tracked};
    use core::marker::PhantomData;
    use core::sync::atomic::{AtomicI64, AtomicU32, Ordering};
    use lightwatch_proto::dist::{bucket_of, bucket_range, MAX_BUCKET};
    use lightwatch_proto::TypeId;

    const BUCKET_COUNT: usize = MAX_BUCKET as usize + 1;

    /// A `bucket` that no counter was incremented for, so `Drop` decrements
    /// nothing. Real bucket indices never reach it.
    const NO_BUCKET: u16 = u16::MAX;

    /// One tracked type's process-wide counters. Generated as a `static`, one
    /// per type, so a construction is a pair of relaxed atomic adds against a
    /// fixed address rather than a lookup.
    pub struct TypeSlot {
        name: &'static str,
        file: &'static str,
        line: u32,
        /// Assigned on first construction. Zero means unregistered; the stored
        /// value is the wire id.
        id: AtomicU32,
        /// Signed so a bookkeeping bug reads as a negative number instead of
        /// wrapping to something enormous.
        live: AtomicI64,
        buckets: [AtomicU32; BUCKET_COUNT],
    }

    impl TypeSlot {
        pub const fn new(name: &'static str, file: &'static str, line: u32) -> Self {
            TypeSlot {
                name,
                file,
                line,
                id: AtomicU32::new(0),
                live: AtomicI64::new(0),
                buckets: [const { AtomicU32::new(0) }; BUCKET_COUNT],
            }
        }

        pub(crate) fn name(&self) -> &'static str {
            self.name
        }

        pub(crate) fn file(&self) -> &'static str {
            self.file
        }

        pub(crate) fn line(&self) -> u32 {
            self.line
        }

        pub(crate) fn interned_id(&self) -> Option<TypeId> {
            match self.id.load(Ordering::Relaxed) {
                0 => None,
                assigned => Some(TypeId(assigned)),
            }
        }

        pub(crate) fn publish_id(&self, id: TypeId) {
            self.id.store(id.0, Ordering::Release);
        }

        fn id(&'static self) -> TypeId {
            self.interned_id()
                .unwrap_or_else(|| crate::registry::intern_type(self))
        }

        pub(crate) fn live(&self) -> u64 {
            self.live.load(Ordering::Relaxed).max(0) as u64
        }

        /// Sparse, sorted, and non-empty buckets only, matching the wire shape.
        pub(crate) fn size_buckets(&self) -> Vec<(u16, u32)> {
            self.buckets
                .iter()
                .enumerate()
                .filter_map(|(index, count)| match count.load(Ordering::Relaxed) {
                    0 => None,
                    n => Some((index as u16, n)),
                })
                .collect()
        }
    }

    /// Total footprint of the live instances.
    ///
    /// Reconstructed from the histogram, because a [`Census`] keeps only its
    /// bucket index. Each bucket contributes its midpoint, so the total is
    /// exact below 32 bytes and within 3.2% above it.
    pub(crate) fn bytes_from_buckets(buckets: &[(u16, u32)]) -> u64 {
        buckets
            .iter()
            .map(|(index, count)| {
                let (lo, hi) = bucket_range(*index);
                (lo + (hi - lo) / 2) * *count as u64
            })
            .sum()
    }

    /// A live-instance token. Two bytes: the bucket its construction
    /// incremented, so `Drop` decrements that same bucket even though the
    /// instance may have grown since.
    pub struct Census<T: Tracked> {
        bucket: u16,
        marker: PhantomData<fn() -> T>,
    }

    impl<T: Tracked> Census<T> {
        /// A value that counts nothing. Only useful for building an instance
        /// whose real size is not known until every other field is in place;
        /// [`track`](crate::track)'s generated constructor overwrites it.
        pub const UNCOUNTED: Self = Census { bucket: NO_BUCKET, marker: PhantomData };

        /// Counts one live instance of `bytes` bytes.
        pub fn from_bytes(bytes: usize) -> Self {
            let slot = T::slot();
            let bucket = bucket_of(bytes as u64);
            slot.live.fetch_add(1, Ordering::Relaxed);
            slot.buckets[bucket as usize].fetch_add(1, Ordering::Relaxed);
            // After the counters, so the emit thread never sees a registered
            // type whose first instance has not landed yet.
            slot.id();
            Census { bucket, marker: PhantomData }
        }

        /// Counts one live instance, sized through [`Measured`].
        ///
        /// Takes the value by reference and never calls `bytes` when the
        /// feature is off, so an expensive `bytes` costs nothing in a build
        /// that is not measuring.
        #[inline]
        pub fn measuring(value: &T) -> Self
        where
            T: Measured,
        {
            Self::from_bytes(value.bytes())
        }
    }

    impl<T: Tracked> Drop for Census<T> {
        fn drop(&mut self) {
            if self.bucket == NO_BUCKET {
                return;
            }
            let slot = T::slot();
            slot.live.fetch_sub(1, Ordering::Relaxed);
            slot.buckets[self.bucket as usize].fetch_sub(1, Ordering::Relaxed);
        }
    }

    /// A clone is another live instance, of the same size.
    impl<T: Tracked> Clone for Census<T> {
        fn clone(&self) -> Self {
            if self.bucket == NO_BUCKET {
                return Census::UNCOUNTED;
            }
            let slot = T::slot();
            slot.live.fetch_add(1, Ordering::Relaxed);
            slot.buckets[self.bucket as usize].fetch_add(1, Ordering::Relaxed);
            Census { bucket: self.bucket, marker: PhantomData }
        }
    }

    impl<T: Tracked> Default for Census<T> {
        /// `size_of::<T>()`, because a derived `Default` has no value to
        /// measure. Prefer the generated `new_tracked`.
        fn default() -> Self {
            Self::from_bytes(core::mem::size_of::<T>())
        }
    }
}

#[cfg(not(feature = "enabled"))]
mod imp {
    use super::{Measured, Tracked};
    use core::marker::PhantomData;

    /// Zero-sized when the feature is off, and with no `Drop`, so a tracked
    /// struct has the same layout and the same drop glue it would have had
    /// without the attribute.
    pub struct TypeSlot;

    impl TypeSlot {
        pub const fn new(_name: &'static str, _file: &'static str, _line: u32) -> Self {
            TypeSlot
        }
    }

    pub struct Census<T: Tracked> {
        marker: PhantomData<fn() -> T>,
    }

    impl<T: Tracked> Census<T> {
        pub const UNCOUNTED: Self = Census { marker: PhantomData };

        #[inline]
        pub fn from_bytes(_bytes: usize) -> Self {
            Census { marker: PhantomData }
        }

        #[inline]
        pub fn measuring(_value: &T) -> Self
        where
            T: Measured,
        {
            Census { marker: PhantomData }
        }
    }

    impl<T: Tracked> Clone for Census<T> {
        fn clone(&self) -> Self {
            Census { marker: PhantomData }
        }
    }

    impl<T: Tracked> Default for Census<T> {
        fn default() -> Self {
            Census { marker: PhantomData }
        }
    }
}

pub use imp::{Census, TypeSlot};

#[cfg(feature = "enabled")]
pub(crate) use imp::bytes_from_buckets;

// A tracked struct still derives what it derived before the attribute, so the
// census field has to satisfy those derives without contributing to them.
impl<T: Tracked> core::fmt::Debug for Census<T> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("Census")
    }
}

impl<T: Tracked> PartialEq for Census<T> {
    fn eq(&self, _other: &Self) -> bool {
        true
    }
}

impl<T: Tracked> Eq for Census<T> {}

impl<T: Tracked> core::hash::Hash for Census<T> {
    fn hash<H: core::hash::Hasher>(&self, _state: &mut H) {}
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Probe;

    impl Tracked for Probe {
        fn slot() -> &'static TypeSlot {
            static SLOT: TypeSlot = TypeSlot::new("Probe", file!(), line!());
            &SLOT
        }
    }

    // PhantomData<fn() -> T> rather than PhantomData<T>: a census token holds
    // no T, so it stays Send and Sync whatever T is.
    #[test]
    fn a_census_is_send_and_sync_regardless_of_its_type() {
        fn assert_send_sync<X: Send + Sync>() {}
        assert_send_sync::<Census<Probe>>();
    }

    #[cfg(not(feature = "enabled"))]
    #[test]
    fn a_census_costs_nothing_when_the_feature_is_off() {
        assert_eq!(core::mem::size_of::<Census<Probe>>(), 0);
        assert!(!core::mem::needs_drop::<Census<Probe>>());
    }

    #[cfg(feature = "enabled")]
    #[test]
    fn a_census_is_two_bytes_when_the_feature_is_on() {
        assert_eq!(core::mem::size_of::<Census<Probe>>(), 2);
    }

    #[cfg(feature = "enabled")]
    #[test]
    fn total_bytes_are_exact_below_the_linear_limit() {
        use lightwatch_proto::dist::bucket_of;
        let buckets = vec![(bucket_of(8), 3u32), (bucket_of(20), 1)];
        assert_eq!(bytes_from_buckets(&buckets), 8 * 3 + 20);
    }

    #[cfg(feature = "enabled")]
    #[test]
    fn total_bytes_stay_within_the_bucketing_error_above_it() {
        use lightwatch_proto::dist::bucket_of;
        let reported = bytes_from_buckets(&[(bucket_of(1_000_000), 4)]);
        let truth = 4_000_000f64;
        assert!(
            (reported as f64 - truth).abs() / truth <= 0.032,
            "{reported} is further than 3.2% from {truth}"
        );
    }
}
